//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SandboxDatabaseManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SandboxDatabaseManager.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DSAKeyValue&gt;&lt;P&gt;mBcwb6hehNoDM5kK9HX+W2oIAP3L+LqtEufO94Iqz1qQqy8g5OtX0wETBLpOsxsAUmhVKpG2xHiG+anU9vJjybr7G6ZAsFWUSSd/3mzE4HLR8P4jKbe3RTuNSKzbUW+6ESRharHj0F33UzfUmf8xZnXvW3PHb6pDCcbCPvPDZC0=&lt;/P&gt;&lt;Q&gt;7oo44BY/fXezsLvY9GRDTPiDHu0=&lt;/Q&gt;&lt;G&gt;jlGzCyAUK8fKZEE7s9GPsAYB3qHxrgqIyNr9nj77f+Y0tjD8ZHaYA/MeJF9l1GdyC3tRCavqdlnhPX/Rx/KPmaEW2Gr3q5h7p9AnrrTuESYOWMq369xwHOLs7IcK0jTSwpnofLnkI5C5VoLS3gUCj3tiuPSSPE9V/Jjxt+rBU2Q=&lt;/G&gt;&lt;Y&gt;Wgc6eoAq0tDX6dvO8Wkm02j51mlPSre+740LhgX0p7LPuJ9z5gTSgMDdYOAvLIxKTbQHvyQqZWrFNbfp0FG7iz/ZTLws12xKkHUWMnc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string publicKey {
            get {
                return ResourceManager.GetString("publicKey", resourceCulture);
            }
        }
    }
}
